version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: arootpassword
      MYSQL_DATABASE: phantacom
      MYSQL_USER: phantacom
      MYSQL_PASSWORD: pH1983

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "2001:80"
    volumes:
      - /sessions

  web:
    depends_on:
      - db
    image: ftertre/damp
    links:
      - db
    ports:
      - "2000:80"
    volumes:
      - "./html:/var/www/html"
  
  api:
    depends_on:
      - db
    image: ftertre/damp
    links:
      - db
    ports:
      - "2002:80"
    volumes:
      - "./api:/var/www"
